# Generated by Django 5.0.6 on 2024-07-25 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medtracker', '0002_medicine_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='description',
            new_name='composition',
        ),
    ]
