# Generated by Django 5.0.6 on 2024-07-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medtracker', '0003_rename_description_medicine_composition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosage',
            name='frequency',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
