# Generated by Django 5.0.6 on 2024-07-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medtracker', '0004_alter_dosage_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosage',
            name='frequency',
            field=models.IntegerField(),
        ),
    ]
